// —————————————————————————————————————————————————————————————————————————————
// DO NOT EDIT THIS FILE!
// —————————————————————————————————————————————————————————————————————————————

import { test } from "uvu";
import * as assert from "uvu/assert";
import { getData, setData } from "./freeze.mjs";

/**
 * @returns {Readonly<{}>}
 */
function createOpaqueObject() {
  return Object.freeze(Object.create(null));
}

test("basic usage", () => {
  let object = createOpaqueObject();
  setData(object, 0);
  assert.is(getData(object), 0);
  setData(object, 1);
  assert.is(getData(object), 1);
});

test("multiple objects", () => {
  let obj1 = createOpaqueObject();
  let obj2 = createOpaqueObject();
  setData(obj1, "foo");
  assert.is(getData(obj1), "foo");
  assert.not(getData(obj2));
  setData(obj2, "bar");
  assert.is(getData(obj2), "bar");
});

test.run();
