// —————————————————————————————————————————————————————————————————————————————
// DO NOT EDIT THIS FILE!
// —————————————————————————————————————————————————————————————————————————————

/**
 * Asserts that `callback` completes with `delay` milliseconds.
 *
 * @param delay The delay in milliseconds.
 * @param callback The function to complete.
 */
export function timeout(
  delay: number,
  callback: () => Promise<unknown>
): Promise<void>;
